name: Deploy test-test
on:
  push:
    branches:
      - test-test

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Subfolder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          target-folder: test-test
          branch: test # זה ידחוף את התיקייה לתוך ה-test שלך
